# Generated by Django 5.0.7 on 2024-08-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doddy", "0003_auction_farmtype_doddyuser_bbc_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doddyuser",
            name="balance",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Berry Balance"
            ),
        ),
    ]
