# Generated by Django 5.0.7 on 2024-08-03 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doddy", "0004_alter_doddyuser_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 3, 21, 1, 0, 607453, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AddField(
            model_name="farmtype",
            name="cost_to_upgrade",
            field=models.PositiveBigIntegerField(
                default=50000, verbose_name="Cost to Upgrade"
            ),
            preserve_default=False,
        ),
    ]
