# Generated by Django 5.0.7 on 2024-08-03 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doddy", "0005_auction_date_farmtype_cost_to_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 3, 21, 23, 59, 656848, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="doddyuser",
            name="last_energy",
            field=models.FloatField(default=1000, verbose_name="Last Energy"),
        ),
    ]
