# Generated by Django 5.0.7 on 2024-08-04 10:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doddy", "0006_alter_auction_date_alter_doddyuser_last_energy"),
    ]

    operations = [
        migrations.AddField(
            model_name="doddyuser",
            name="last_farm_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Energy Last Updated"
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 4, 10, 27, 0, 630845, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
    ]
