# Generated by Django 5.0.7 on 2024-09-02 18:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doddy', '0007_doddyuser_last_farm_datetime_alter_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doddyuser',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 12, 13, 260823, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
